apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: tzmzfad18-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: tzmzfad18-go 
  name: tzmzfad18-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: tzmzfad18-go 
